# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.0

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["terraform fmt -check"]
  runner_image: hashicorp/terraform:light

# The set of tests to run to verify your module works correctly
tests:
  - name: module
    project_root: ../