# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.1

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["terraform fmt -check"]
  runner_image: hashicorp/terraform:light

# The set of tests to run to verify your module works correctly
tests:
  - name: Test the module with 1.1.16
    terraform_version: 1.1.16
    environment:
      TF_VAR_domain_name: test_domain.com
      TF_VAR_bucket_name: test_bucket
      
  - name: Ensure that the submodule can fail
    # You can use negative to indicate that the test case is expected to fail
    negative: true
    terraform_version: 0.13.0